### PR TITLE
Fix approval button & styling fixes

### LINKED ISSUE #39: Approve Button Not working
image

### PR DESCRIPTION
**Pull request by Phineas**
Fixes #39 
closes: #61
closes: #47
closes: #60

Also a few layout/display fixes & code cleanup

### CODE REVIEW

File: client/src/app/detail.js [hunk 1]
```diff
@@ -295,20 +261,6 @@ const Detail = observer((props) => {
...
-                                    >
-                                      <span className="waifu-button-learnmore">
-                                        {" "}
-                                        Approve
-                                      </span>{" "}
-                                    </Button.Outline>
-                                  </Box>
-                                )}
-                                {detailStore.isApproved && (
                                   <center>
```
Comment (chase-manning) [inline client/src/app/detail.js:264]: @Phineas  doesn't this remove the ability for the user to approve?

Comment (Phineas) [reply client/src/app/detail.js:264]: Excuse my lack of Web3 knowledge haha, I know approval is needed for the first time a user connects their wallet provider but it's not needed after they've already made the first approval, right? We should probably store their approval status in the state

Comment (Phineas) [reply client/src/app/detail.js:299]: I've added it back and call it before the modal is shown just to make sure we run into any inconsistencies in my latest commit

**Review by chase-manning — APPROVED** [review]
